// Generated by Supabase MCP — do not edit by hand.
// Regenerate via `mcp__supabase__generate_typescript_types`.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      couple_invites: {
        Row: {
          code: string
          created_at: string
          created_by: string
          expires_at: string
          id: string
          used_at: string | null
          used_by: string | null
        }
        Insert: {
          code: string
          created_at?: string
          created_by: string
          expires_at?: string
          id?: string
          used_at?: string | null
          used_by?: string | null
        }
        Update: {
          code?: string
          created_at?: string
          created_by?: string
          expires_at?: string
          id?: string
          used_at?: string | null
          used_by?: string | null
        }
        Relationships: []
      }
      couples: {
        Row: {
          created_at: string
          id: string
          reunion_date: string | null
          user1_id: string
          user2_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          reunion_date?: string | null
          user1_id: string
          user2_id: string
        }
        Update: {
          created_at?: string
          id?: string
          reunion_date?: string | null
          user1_id?: string
          user2_id?: string
        }
        Relationships: []
      }
      drawings: {
        Row: {
          couple_id: string
          id: string
          paths_json: Json
          sender_id: string
          sent_at: string
        }
        Insert: {
          couple_id: string
          id?: string
          paths_json: Json
          sender_id: string
          sent_at?: string
        }
        Update: {
          couple_id?: string
          id?: string
          paths_json?: Json
          sender_id?: string
          sent_at?: string
        }
        Relationships: []
      }
      heartbeats: {
        Row: {
          couple_id: string
          id: string
          sender_id: string
          sent_at: string
        }
        Insert: {
          couple_id: string
          id?: string
          sender_id: string
          sent_at?: string
        }
        Update: {
          couple_id?: string
          id?: string
          sender_id?: string
          sent_at?: string
        }
        Relationships: []
      }
      memory_jar_notes: {
        Row: {
          body: string
          couple_id: string
          created_at: string
          id: string
          opened_at: string | null
          sender_id: string
        }
        Insert: {
          body: string
          couple_id: string
          created_at?: string
          id?: string
          opened_at?: string | null
          sender_id: string
        }
        Update: {
          body?: string
          couple_id?: string
          created_at?: string
          id?: string
          opened_at?: string | null
          sender_id?: string
        }
        Relationships: []
      }
      moods: {
        Row: {
          couple_id: string
          emoji: string | null
          id: string
          mood: string
          sender_id: string
          sent_at: string
        }
        Insert: {
          couple_id: string
          emoji?: string | null
          id?: string
          mood: string
          sender_id: string
          sent_at?: string
        }
        Update: {
          couple_id?: string
          emoji?: string | null
          id?: string
          mood?: string
          sender_id?: string
          sent_at?: string
        }
        Relationships: []
      }
      photos: {
        Row: {
          couple_id: string
          id: string
          sender_id: string
          sent_at: string
          storage_path: string
          tag: string | null
        }
        Insert: {
          couple_id: string
          id?: string
          sender_id: string
          sent_at?: string
          storage_path: string
          tag?: string | null
        }
        Update: {
          couple_id?: string
          id?: string
          sender_id?: string
          sent_at?: string
          storage_path?: string
          tag?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          id: string
          name?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      time_capsules: {
        Row: {
          body: string
          couple_id: string
          created_at: string
          id: string
          open_at: string
          opened_at: string | null
          sender_id: string
        }
        Insert: {
          body: string
          couple_id: string
          created_at?: string
          id?: string
          open_at: string
          opened_at?: string | null
          sender_id: string
        }
        Update: {
          body?: string
          couple_id?: string
          created_at?: string
          id?: string
          open_at?: string
          opened_at?: string | null
          sender_id?: string
        }
        Relationships: []
      }
      together_state: {
        Row: {
          active: boolean
          couple_id: string
          since: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          active?: boolean
          couple_id: string
          since?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          active?: boolean
          couple_id?: string
          since?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      widget_config: {
        Row: {
          countdown_enabled: boolean
          distance_enabled: boolean
          drawing_enabled: boolean
          home_screen: boolean
          lock_screen: boolean
          photo_enabled: boolean
          theme: string
          updated_at: string
          user_id: string
        }
        Insert: {
          countdown_enabled?: boolean
          distance_enabled?: boolean
          drawing_enabled?: boolean
          home_screen?: boolean
          lock_screen?: boolean
          photo_enabled?: boolean
          theme?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          countdown_enabled?: boolean
          distance_enabled?: boolean
          drawing_enabled?: boolean
          home_screen?: boolean
          lock_screen?: boolean
          photo_enabled?: boolean
          theme?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      generate_invite_code: { Args: never; Returns: string }
      is_couple_member: { Args: { p_couple_id: string }; Returns: boolean }
      use_invite_code: { Args: { p_code: string }; Returns: Json }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
